### ISSUE TITLE
Comments/Suggestions

### ISSUE THREAD

**Issue by kbond** [vinkla/backup#1]
This looks good as a quick and dirty solution.

Here are some suggestions to make it more extensible:

1. Multiple profiles? I would suggest leveraging the `ProfileRegistry` from `zenstruck/backup`
2. `zenstruck/backup` comes with a `FlysystemDestination` - perhaps you can use that instead of using `StreamDestination`?
3. If you choose to use the `ProfileRegistry`, then your command can extend the `RunCommand` from `zenstruck/backup` and also use the `ListCommand`

**Comment by vinkla** [comment]
1. Instead of looping the connections I would instead loop through the profiles?
2. Yeah, I just forgot to change the class. Fixed now :)
3. Not sure how I would implement it. Any ideas?

**Comment by kbond** [comment]
In the symfony bundle, you configure all available sources/destinations/namers/processors. These are created from the config, then added to the `ProfileBuilder`.

You then configure your profiles, using the names of the sources/destinations/namers/processors you defined above. These profiles are built using `ProfileBuilder::create()` and added to the `ProfileRegistry`.

The completed `ProfileRegistry` is then used by the commands.

(Of course all this is done lazily)

**Comment by vinkla** [comment]
Okay, would this mean the profiles would be added to the config file?

**Comment by kbond** [comment]
I imagine the laravel config would look something like the following:

```php
return [
    // this part tells you how to build the items
    'destinations' => [
        'my_local_dest' => ['type' => 'stream', 'path' => storage_path()]
    ],
    'sources' => [
        'my_database_source' => [/* ... */],
        'my_files_source' => [/* ... */]
    ],
    'namers' => [
        'namer1' => [/* ... */]
        'namer2' => [/* ... */]
    ],
    'processors' => [
        'zip' => [/* ... */]
    ],

    // here we configure the available profiles using the above config
    'profiles' => [
        'my_profile1' => [
            'namer' => 'namer1',
            'processor' => 'zip',
            'sources' => ['my_database_source', 'my_files_source'],
            'destinations' => ['my_local_dest'],
        ]
    ]
]
```

**Comment by vinkla** [comment]
I would like to make it as easy as possible to add it to Laravel. Using Laravel's built in functionality to make the most out of your package and this one.

**Comment by vinkla** [comment]
What is the `[/* ... */]` part? Is that the classes?

**Comment by kbond** [comment]
> I would like to make it as easy as possible to add it to Laravel. Using Laravel's built in functionality to make the most out of your package and this one.

Yeah, there is probably going to be a trade-off. Have it work out of the box with very little config or highly customizable with a ton of config... Ultimately, that will be up to you.

Maybe there is a way to have both? Perhaps have all the customization with an out of the box default?

**Comment by vinkla** [comment]
> Maybe there is a way to have both? Perhaps have all the customization with an out of the box default?

Yeah, that idea I do like. Don't get me wrong, I like your setup. I'm just not sure how to implement it yet.

**Comment by kbond** [comment]
> What is the [/* ... */] part? Is that the classes?

In my example, that would be the scalar configuration for each item. `my_local_dest` is a full example: The type tells you to use `StreamDestination`, the rest of the array values are the arguments for `StreamDestination`.

**Comment by kbond** [comment]
You could also have the user actually build the classes themselves:

```php
return [
    // this part tells you how to build the items
    'destinations' => [
        new StreamDestination('my_local_dest', storage_path()),
        // ...
    ],
    // ...
];
```

I am not sure how feasible this would be with laravel as you might need access to 3rd party stuff like for flysystem. This type of setup wouldn't work in Symfony.

**Comment by vinkla** [comment]
Would this also be a good idea then?

```php
return [
    'destinations' => [
        'local' => [
            'type' => 'Zenstruck\Backup\Destination\StreamDestination', 
            'path' => storage_path()
        ]
    ],
];
```

**Comment by kbond** [comment]
Sure, that works as well. You could use reflection to determine how to build the object. This would be neat as it is extensible: end users can add their own destinations:

```php
return [
    'destinations' => [
        'local' => [
            'type' => 'My\Cool\Destination', 
            'path' => storage_path()
        ]
    ],
];
```

I would suggest having some out of the box type "shortcuts" - that way the user doesn't need to know the fully qualified class name:

```php
return [
    'destinations' => [
        'local' => [
            'type' => 'stream', 
            'path' => storage_path()
        ]
    ],
];
```

When building the object, you can have a lookup of your shortcuts.

Now, would this work with the `FlysystemDestination`?

**Comment by kbond** [comment]
> Yeah, I don't like creating classes within the Laravel config. That is usually not such a good idea.

I figured that would be considered bad practice.

**Comment by vinkla** [comment]
I guess we need to create a custom FlysystemDestination. The package could use (or suggest) the [Laravel Flysystem integration package](https://github.com/GrahamCampbell/Laravel-Flysystem). In this way to could just fetch the default Flysystem integration by running `Flysystem::connection()`.

Also, maybe we could even create `DropboxDestination`, `FtpDestination`, `SftpDestination`, etc. To simplify the setup process even more?

**Comment by kbond** [comment]
> Also, maybe we could even create DropboxDestination, FtpDestination, SftpDestination, etc. To simplify the setup process even more?

Doesn't Flysystem have adapters for these?

I have some discussion with another zenstruck/backup contributor about adding Flysystem as a hard dependency. Flysystem is pretty stable and becoming the de faco standard for managing different filesystems. It is really outside of the scope of zenstruck/backup to manage different filesystems.

This will require a significant refactor so it wouldn't happen in the near future.

**Comment by kbond** [comment]
> I guess we need to create a custom FlysystemDestination

My concern is with accessing services (?) from other service providers within config. I'm guessing it is not possible.

**Comment by vinkla** [comment]
> Doesn't Flysystem have adapters for these?

Yeah, I mean we add these adapters to this package as well. Then we can just utilize the Laravel Flysystem package like this:

```php
class DropboxDestination extends AbstractDestination {

    public function make(array $config) 
    {
        return new FlysystemDestination(
            $config['name'], 
            $this->flysystem->connection($config['name'])
        );
    }

}
```

What do you think?

**Comment by kbond** [comment]
The way the Symfony config works for Flysystem is you reference a filesystem service name in the config:

```php
return [
    'destinations' => [
        'local' => [
            'type' => 'flysystem', 
            'filesystem' => 'specific_filesystem_service_configured_elsewhere'
        ]
    ],
];
```

I'm not sure this could work in laravel, does it have a service registry of some kind?

**Comment by kbond** [comment]
> What do you think?

I'm not sure why you would create a `DropboxDestination` class... I would just do:

```php
$destination = new FlysystemDestination(
            $config['name'], 
            $this->flysystem->connection($config['connection'])
        );
```

**Comment by kbond** [comment]
The code for the configuration in my Symfony backup bundle is really complex... I know there is no simple solution if you want to be extensible.

**Comment by vinkla** [comment]
> I'm not sure why you would create a DropboxDestination class... I would just do:

Yeah, the class would be simple but it would be easy to setup:

```php
return [
    'destinations' => [
        'local' => [
            'type' => 'flysystem', 
            'filesystem' => 'Vinkla\Backup\Destinations\DropboxDestination'
        ]
    ],
];
```

**Comment by kbond** [comment]
> Yeah, the class would be simple but it would be easy to setup

But you would have to create a class for every existing and future Flystsem adapter. Why not just use the connection key:

```php
// config:
return [
    'destinations' => [
        'local' => [
            'type' => 'flysystem', 
            'filesystem_connection' => 'dropbox_connection'
        ]
    ],
];

// code that builds destinations:
$destinationInstances = [];

foreach ($destinations as $name => $config) {
    if ('flysystem' === $config['type']) {
        $destinationInstances[] = new FlysystemDestination($name, $config['filesystem_connection']);
        continue;
    }
    // ...
}
// ...
```

**Comment by vinkla** [comment]
Yeah, you are right. I'm not thinking clearly.

**Comment by kbond** [comment]
To really simplify things, I would suggest only allowing flysystem destinations:

```php
return [
    'destinations' => [
        'dropbox' => 'dropbox_flysystem_connection_key',
        's3' => 's3_flysystem_connection_key',
    ],
];
```

**Comment by vinkla** [comment]
To be honest I think it would nice to just have the profiles list in the configuration and everything else in the code. Of course still extensible but out of the box it just shows the profiles with destinations and sources:

```php
return [
  'profiles' => [
    'my_profile1' => [
      'sources' => [storage_path(), app_path()],
      'destinations' => ['local', 'dropbox'],
    ]
  ]
];
```

This is similar to my current setup. My current setup is still extensible but it doesn't show it out of the box.

**Comment by kbond** [comment]
Sure, you can have a hard-coded default namer and processor. What about hard-coding a storage_path, app_path and database source. Then the user can reference it in config:

```php
return [
  'profiles' => [
    'full_backup' => [
      'sources' => ['storage_path', 'app_path', 'database'],
      'destinations' => ['local', 'dropbox'],
    ],
    'just_database' => [
      'sources' => ['database'],
      'destinations' => ['local', 'dropbox'],
    ]
  ]
];
```

**Comment by vinkla** [comment]
Yeah, that is a good idea.

**Comment by vinkla** [comment]
How would you go about adding the `ProfileRegistry` and the `ProfileBuilder`?

**Comment by kbond** [comment]
If the user doesn't define `sources`, default to `['storage_path', 'app_path', 'database']`

**Comment by vinkla** [comment]
Yeah, sounds good.

**Comment by kbond** [comment]
> How would you go about adding the ProfileRegistry and the ProfileBuilder?

I'm not quite sure, somewhere you have to make `ProfileRegistry` available as a service. This service needs to be built from the config. In `BackupServiceProvider`, can you add a `registerProfileRegistry` method and build the `ProfileRegistry` there?

**Comment by kbond** [comment]
The creation of the service would look something like this:

```php
$profileBuilder = new ProfileBuilder(
    [new ZipArchiveProcessor('zip')],
    // all your hard coded stuff
);

$profileRegistry = new ProfileRegistry();

foreach ($config['profiles'] as $name => $profileConfig) {
    if (!isset($profileConfig['sources']) {
        $profileConfig['sources'] = // default sources...
    }

    $profileRegistry->add($profileBuilder->create($name, $profileConfig['namer'], /* ... */);
}

// register $profileRegistry
```

**Comment by vinkla** [comment]
Then within the command we need to fetch the profile registry somehow. Though, wouldn't the `BackupServiceProvider` become huge?

**Comment by vinkla** [comment]
Maybe I can split it up somehow.

**Comment by kbond** [comment]
Yes, it would be large, maybe you could create a `ProfileRegistryFactory`? I think you can remove `BackupManager`, BackupFactory` and `Backup`.

`BackupServiceProvider` would provide an executor service, a profile registry service and the command(s).

**Comment by vinkla** [comment]
Okay, I'll try refactoring the package tomorrow. Thanks for all your help and suggestions today, really appreciate it! Maybe we could Skype or Slack in the future?

**Comment by kbond** [comment]
No problem!

**Comment by vinkla** [comment]
Closing this.
